using System.Collections.Generic;

namespace Palett {
  public static partial class Pavtone {
    public static readonly Dictionary<string, string> Products = new Dictionary<string, string> {
      { "#005A92", "Imperial Blue" },
      { "#006361", "Teal Green" },
      { "#006CA9", "Indigo Bunting" },
      { "#007290", "Fjord Blue" },
      { "#0074A8", "Methyl Blue" },
      { "#0075B3", "Brilliant Blue" },
      { "#007BAA", "Blue Jewel" },
      { "#008658", "Jelly Bean" },
      { "#0086BB", "Dresden Blue" },
      { "#008DB9", "Hawaiian Ocean" },
      { "#009473", "Emerald" },
      { "#034F84", "Snorkel Blue" },
      { "#097988", "Biscay Bay" },
      { "#0A6F69", "Tidepool" },
      { "#0F9D76", "Holly Green" },
      { "#149C88", "Sea Green" },
      { "#14A3C7", "Cyan Blue" },
      { "#18454B", "Deep Teal" },
      { "#18576C", "Corsair" },
      { "#1A5091", "Nautical Blue" },
      { "#243F6C", "Limoges" },
      { "#264A48", "June Bug" },
      { "#279D9F", "Baltic" },
      { "#289DBE", "Horizon Blue" },
      { "#29685F", "Galapagos Green" },
      { "#2A3244", "Dress Blues" },
      { "#2A5C6A", "Dragonfly" },
      { "#2B3042", "Black Iris" },
      { "#2BAE66", "Island Green" },
      { "#2EA785", "Gumdrop Green" },
      { "#325B74", "Midnight" },
      { "#32BECC", "Blue Curacao" },
      { "#335959", "Jasper" },
      { "#339C5E", "Kelly Green" },
      { "#343148", "Eclipse" },
      { "#35463D", "Sycamore" },
      { "#363151", "Astral Aura" },
      { "#363838", "Pirate Black" },
      { "#37503D", "Greener Pastures" },
      { "#3850A0", "Dazzling Blue" },
      { "#38AFCD", "River Blue" },
      { "#39373B", "Phantom" },
      { "#395551", "Bistro Green" },
      { "#3A3536", "Licorice" },
      { "#3A4032", "Kombu Green" },
      { "#3AB0A2", "Waterfall" },
      { "#3C3535", "After Dark" },
      { "#3C3F4A", "India Ink" },
      { "#3C7D90", "Larkspur" },
      { "#3D5E8C", "Delft" },
      { "#3E524B", "Garden Topiary" },
      { "#3E6F58", "Foliage Green" },
      { "#3E7FA5", "Cendre Blue" },
      { "#40312F", "Coffee Bean" },
      { "#40A48E", "Marine Green" },
      { "#413E3D", "Raven" },
      { "#41424A", "Ebony" },
      { "#433748", "Nightshade" },
      { "#434237", "Forest Night" },
      { "#43628B", "Federal Blue" },
      { "#436573", "Tapestry" },
      { "#44413C", "Black Ink" },
      { "#45B5AA", "Turquoise" },
      { "#46394B", "Mysterioso" },
      { "#46434A", "Nine Iron" },
      { "#46647E", "Stellar" },
      { "#473854", "Purple Plumeria" },
      { "#473951", "Gothic Grape" },
      { "#477050", "Fairway" },
      { "#47788A", "Storm Blue" },
      { "#478589", "Teal" },
      { "#483F39", "Turkish Coffee" },
      { "#48413B", "Black Olive" },
      { "#493B39", "Seal Brown" },
      { "#4A3F41", "Shale" },
      { "#4A4139", "Wren" },
      { "#4A4843", "Beluga" },
      { "#4A4B4D", "Dark Shadow" },
      { "#4ABBD5", "Bachelor Button" },
      { "#4B3D33", "Slate Black" },
      { "#4B9B69", "Greenbriar" },
      { "#4BC3A8", "Electric Green" },
      { "#4C6969", "Sea Pine" },
      { "#4D495B", "Graystone" },
      { "#4D91C6", "Azure Blue" },
      { "#4E334E", "Shadow Purple" },
      { "#4E403B", "Chocolate Brown" },
      { "#4E5E7F", "Bijou Blue" },
      { "#4F6B58", "Myrtle" },
      { "#4F7C74", "Deep Sea" },
      { "#4F7CA4", "Parisian Blue" },
      { "#503938", "Puce" },
      { "#50574C", "Thyme" },
      { "#505D7E", "Coastal Fjord" },
      { "#515B87", "Marlin" },
      { "#52A2B4", "Maui Blue" },
      { "#533D7D", "Prism Violet" },
      { "#539CCC", "Bonnie Blue" },
      { "#53B0AE", "Blue Turquoise" },
      { "#5487A4", "Niagara" },
      { "#549F98", "Sea Blue" },
      { "#553B39", "Deep Mahogany" },
      { "#556962", "Dark Forest" },
      { "#558367", "Deep Grass Green" },
      { "#558F91", "Bristol Blue" },
      { "#55A860", "Vibrant Green" },
      { "#55C6A9", "Biscay Green" },
      { "#567572", "Sagebrush Green" },
      { "#56BEAB", "Florida Keys" },
      { "#578270", "Frosty Spruce" },
      { "#584039", "Chestnut" },
      { "#585442", "Ivy Green" },
      { "#5879A2", "Riviera" },
      { "#58C8B6", "Cockatoo" },
      { "#59728E", "Coronet Blue" },
      { "#59754D", "Willow Bough" },
      { "#5A4743", "Shopping Bag" },
      { "#5A5348", "Tarmac" },
      { "#5A5B9F", "Blue Iris" },
      { "#5A77A8", "Blue Yonder" },
      { "#5B4349", "Huckleberry" },
      { "#5B4F3B", "Beech" },
      { "#5B7E98", "Blue Heaven" },
      { "#5B7EBD", "Ultramarine" },
      { "#5BACC3", "Blue Mist" },
      { "#5C4939", "Dark Earth" },
      { "#5C619D", "Violet Storm" },
      { "#5C6D7C", "Blue Mirage" },
      { "#5C899B", "Adriatic Blue" },
      { "#5CA6CE", "Ethereal Blue" },
      { "#5D473A", "Carafe" },
      { "#5D81BB", "Granada Sky" },
      { "#5D89B3", "Lichen Blue" },
      { "#5D9CA4", "Porcelain" },
      { "#5DAFCE", "Crystal Seas" },
      { "#5E5347", "Canteen" },
      { "#5F4B8B", "Ultra Violet" },
      { "#5F575C", "Rabbit" },
      { "#5F5E62", "Castlerock" },
      { "#5F6DB0", "Baja Blue" },
      { "#5F7278", "Goblin Blue" },
      { "#5F7355", "Vineyard Green" },
      { "#603749", "Prune" },
      { "#604E7A", "Imperial Palace" },
      { "#60569A", "Purple Opulence" },
      { "#60A0A3", "Meadowbrook" },
      { "#60C9B3", "Bermuda" },
      { "#613F4C", "Eggplant" },
      { "#61473B", "Pinecone" },
      { "#616652", "Four Leaf Clover" },
      { "#616F65", "Laurel Wreath" },
      { "#6198AE", "Delphinium Blue" },
      { "#625B5C", "Plum Kitten" },
      { "#625D5D", "Dark Gull Gray" },
      { "#626879", "Folkstone Gray" },
      { "#634F62", "Vintage Violet" },
      { "#6384B8", "Blue Bonnet" },
      { "#646093", "Corsican Blue" },
      { "#647755", "Dill" },
      { "#6479B3", "Wedgewood" },
      { "#648589", "Arctic" },
      { "#64A1AD", "Aqua" },
      { "#64BFA4", "Spearmint" },
      { "#65769A", "Colony Blue" },
      { "#658DC6", "Provence" },
      { "#658E67", "Stone Green" },
      { "#664238", "Brunette" },
      { "#666564", "Pewter" },
      { "#66BC91", "Katydid" },
      { "#67592A", "Fir Green" },
      { "#675A74", "Mulled Grape" },
      { "#676168", "Excalibur" },
      { "#67BCB3", "Pool Blue" },
      { "#685E4F", "Stone Gray" },
      { "#686767", "Gargoyle" },
      { "#686D6C", "Sedona Sage" },
      { "#69595C", "Sparrow" },
      { "#695E4B", "Capers" },
      { "#696156", "Bungee Cord" },
      { "#696BA0", "Dusted Peri" },
      { "#699158", "Fluorite Green" },
      { "#6A8988", "Trellis" },
      { "#6B8D53", "Forest Green" },
      { "#6C6868", "Charcoal Gray" },
      { "#6D636B", "Shark" },
      { "#6D8994", "Smoke Blue" },
      { "#6D9192", "Mineral Blue" },
      { "#6E4C4B", "Marron" },
      { "#6E4F3A", "Bison" },
      { "#6E5C4B", "Cub" },
      { "#6E6E5C", "Deep Lichen Green" },
      { "#6E7E99", "Infinity" },
      { "#6EA2D5", "Little Boy Blue" },
      { "#6F3C56", "Amaranth" },
      { "#6F8C69", "Turf Green" },
      { "#6F8D6A", "Kashmir" },
      { "#6F9FA9", "Reef Waters" },
      { "#702F3B", "Cordovan" },
      { "#705861", "Flint" },
      { "#709A89", "Malachite Green" },
      { "#70A4B0", "Stillwater" },
      { "#717E6F", "Sea Spray" },
      { "#717F9B", "Country Blue" },
      { "#7181A4", "English Manor" },
      { "#725440", "Partridge" },
      { "#725E43", "Kangaroo" },
      { "#726F70", "Steel Gray" },
      { "#7291B4", "Allure" },
      { "#72A8BA", "Milky Blue" },
      { "#734B42", "Mink" },
      { "#736253", "Shitake" },
      { "#736460", "Iron" },
      { "#739957", "Meadow Green" },
      { "#745587", "Purple Heart" },
      { "#748C69", "Watercress" },
      { "#755139", "Toffee" },
      { "#75663E", "Nutria" },
      { "#75697E", "Purple Sage" },
      { "#756D47", "Olive Drab" },
      { "#759465", "Jade Green" },
      { "#764F82", "Meadow Violet" },
      { "#765269", "Berry Conserve" },
      { "#767BA5", "Lavender Violet" },
      { "#768A75", "Hedge Green" },
      { "#769358", "Piquant Green" },
      { "#76AFB6", "Marine Blue" },
      { "#76B583", "Absinthe Green" },
      { "#76C1B2", "Cascade" },
      { "#77824A", "Grasshopper" },
      { "#77A276", "Jadesheen" },
      { "#77CFB7", "Opal" },
      { "#788F74", "Loden Frost" },
      { "#795D34", "Breen" },
      { "#79839B", "Tempest" },
      { "#79B465", "Bud Green" },
      { "#79C753", "Green Flash" },
      { "#7A5747", "Aztec" },
      { "#7A898F", "Lead" },
      { "#7A9DCB", "Della Robbia Blue" },
      { "#7ACCB8", "Beveled Glass" },
      { "#7B6660", "Deep Taupe" },
      { "#7BB369", "Grass Green" },
      { "#7BC4C4", "Aqua Sky" },
      { "#7C83BC", "Deep Periwinkle" },
      { "#7C8C87", "Chinois Green" },
      { "#7CB68E", "Light Grass Green" },
      { "#7D956D", "Green Eyes" },
      { "#7E9285", "Green Bay" },
      { "#7ED37F", "Summer Green" },
      { "#7F674F", "Otter" },
      { "#7FBB9E", "Neptune Green" },
      { "#80304C", "Beaujolais" },
      { "#806062", "Rose Taupe" },
      { "#807396", "Purple Haze" },
      { "#80765F", "Covert Green" },
      { "#807D6F", "Vetiver" },
      { "#80817D", "Moon Mist" },
      { "#817A60", "Aloe" },
      { "#817A65", "Mermaid" },
      { "#81894E", "Turtle Green" },
      { "#818F84", "Lily Pad" },
      { "#819548", "Peridot" },
      { "#819AC1", "Bel Air Blue" },
      { "#81A0D4", "Vista Blue" },
      { "#81C3B4", "Holiday" },
      { "#825E2F", "Bronze Brown" },
      { "#82776B", "Brindle" },
      { "#82B185", "Peapod" },
      { "#836B4F", "Ermine" },
      { "#8398CA", "Grapemist" },
      { "#83C2CD", "Antigua Sand" },
      { "#83C5CD", "Angel Blue" },
      { "#847986", "Gray Ridge" },
      { "#847A59", "Dried Herb" },
      { "#84898C", "Monument" },
      { "#854C65", "Damson" },
      { "#85CED1", "Aqua Splash" },
      { "#864D75", "Amethyst" },
      { "#865560", "Renaissance Rose" },
      { "#865E49", "Rawhide" },
      { "#86A293", "Granite Green" },
      { "#86A96F", "Green Tea" },
      { "#874E3C", "Coconut Shell" },
      { "#876155", "Clove" },
      { "#879F84", "Basil" },
      { "#87B9BC", "Aqua Haze" },
      { "#87D7BE", "Cabbage" },
      { "#87D8C3", "Ice Green" },
      { "#884C5E", "Hawthorn Rose" },
      { "#886971", "Grape Shake" },
      { "#8895C5", "Pale Iris" },
      { "#88B04B", "Greenery" },
      { "#895C79", "Argyle Purple" },
      { "#897F98", "Dusk" },
      { "#899BB8", "Forever Blue" },
      { "#89ACAC", "Aquifer" },
      { "#8A6F48", "Dull Gold" },
      { "#8A7963", "Lead Gray" },
      { "#8A9992", "Green Milieu" },
      { "#8A9A9A", "Silver Blue" },
      { "#8AA282", "Mistletoe" },
      { "#8ABAD3", "Sky Blue" },
      { "#8B645A", "Cognac" },
      { "#8B79B1", "Paisley Purple" },
      { "#8B8C89", "Wild Dove" },
      { "#8C373E", "Brick Red" },
      { "#8C4A2F", "Ginger Bread" },
      { "#8C7C61", "Elmwood" },
      { "#8C8EB2", "Persian Violet" },
      { "#8C9C92", "Iceberg Green" },
      { "#8C9CC1", "Lavender Lustre" },
      { "#8D8070", "Timber Wolf" },
      { "#8D8B55", "Green Olive" },
      { "#8DB051", "Parrot Green" },
      { "#8E7C71", "Taupe Gray" },
      { "#8E918F", "Neutral Gray" },
      { "#8F7265", "Brownie" },
      { "#8F7DA5", "Chalk Violet" },
      { "#8F8177", "Fungi" },
      { "#8F8395", "Purple Ash" },
      { "#8F9E9D", "Abyss" },
      { "#909B4C", "Spinach Green" },
      { "#91672F", "Golden Brown" },
      { "#918C7E", "Laurel Oak" },
      { "#918C86", "Rock Ridge" },
      { "#91A8D0", "Serenity" },
      { "#91AC80", "Forest Shade" },
      { "#926AA6", "Amethyst Orchid" },
      { "#92705F", "Raw Umber" },
      { "#927240", "Cumin" },
      { "#927288", "Very Grape" },
      { "#92898A", "Zinc" },
      { "#929090", "Wet Weather" },
      { "#92AF88", "Fair Green" },
      { "#936B4F", "Thrush" },
      { "#936CA7", "Hyacinth" },
      { "#938772", "Coriander" },
      { "#944E87", "Striking Purple" },
      { "#947764", "Woodsmoke" },
      { "#948D99", "Minimal Gray" },
      { "#9499BB", "Thistle Down" },
      { "#953640", "Garnet" },
      { "#957A76", "Antler" },
      { "#959889", "Seagrass" },
      { "#959EB7", "Eventide" },
      { "#95A69F", "Jadeite" },
      { "#95C0CB", "Porcelain Blue" },
      { "#964F4C", "Marsala" },
      { "#96DFCE", "Beach Glass" },
      { "#973A36", "Bossa Nova" },
      { "#973C6C", "Baton Rouge" },
      { "#976F4C", "Chipmunk" },
      { "#977547", "Medal Bronze" },
      { "#97C1A1", "Hemlock" },
      { "#98754A", "Bistre" },
      { "#988088", "Toadstool" },
      { "#9884B9", "Bougainvillea" },
      { "#997867", "Beaver Fur" },
      { "#998978", "Dune" },
      { "#999E98", "Wrought Iron" },
      { "#99C1CC", "Aquatic" },
      { "#99C5C4", "Pastel Turquoise" },
      { "#9A382D", "Ketchup" },
      { "#9A6051", "Copper Brown" },
      { "#9A7352", "Tobacco Brown" },
      { "#9A927F", "Seneca Rock" },
      { "#9AA067", "Fern" },
      { "#9B1B30", "Chili Pepper" },
      { "#9BA9CA", "Brunnera Blue" },
      { "#9BABBB", "Blue Fog" },
      { "#9BB7D4", "Cerulean" },
      { "#9C8E7B", "Chinchilla" },
      { "#9C9B98", "Ghost Gray" },
      { "#9C9BA7", "Dapple Gray" },
      { "#9CAD60", "Herbal Garden" },
      { "#9CC2C5", "Canal Blue" },
      { "#9D7446", "Bone Brown" },
      { "#9D7BB0", "English Lavender" },
      { "#9D96B2", "Heirloom Lilac" },
      { "#9DC3D4", "Aquamarine" },
      { "#9E91C3", "Violet Tulip" },
      { "#9EBC97", "Quiet Green" },
      { "#9EC1CC", "Stratosphere" },
      { "#9F4440", "Tandoori Spice" },
      { "#9F7A93", "Valerian" },
      { "#9F8672", "Amphora" },
      { "#9F8D7C", "Silver Mink" },
      { "#9F9C99", "Paloma" },
      { "#9FC09C", "Sprucestone" },
      { "#9FD9D7", "Blue Tint" },
      { "#A0987C", "Slate Green" },
      { "#A09C98", "Flint Gray" },
      { "#A09D59", "Moss" },
      { "#A09F9C", "Drizzle" },
      { "#A0AC4F", "Dark Citron" },
      { "#A0BCD0", "Dream Blue" },
      { "#A1759C", "Dusty Lavender" },
      { "#A19FA5", "Silver Sconce" },
      { "#A1C8DB", "Crystal Blue" },
      { "#A1D7C9", "Yucca" },
      { "#A22452", "Cherries Jubilee" },
      { "#A2574B", "Etruscan Red" },
      { "#A28776", "Chanterelle" },
      { "#A2919B", "Nirvana" },
      { "#A2A2A1", "Silver" },
      { "#A2B6B9", "Cloud Blue" },
      { "#A2B9C2", "Sterling Blue" },
      { "#A39264", "Khaki" },
      { "#A3A04E", "Oasis" },
      { "#A3B5A6", "Frosty Green" },
      { "#A3BDD3", "Angel Falls" },
      { "#A3C57D", "Opaline Green" },
      { "#A3C893", "Arcadian Green" },
      { "#A3CCC9", "Eggshell Blue" },
      { "#A47149", "Cashew" },
      { "#A47D43", "Wood Thrush" },
      { "#A49887", "Crockery" },
      { "#A4AE77", "Tarragon" },
      { "#A58D7F", "Stucco" },
      { "#A5929D", "Sea Fog" },
      { "#A59788", "Tuffet" },
      { "#A5B2AA", "Aqua Gray" },
      { "#A5B3CC", "Kentucky Blue" },
      { "#A5B8D0", "Cashmere Blue" },
      { "#A5BCBB", "Blue Haze" },
      { "#A5C5D9", "Cool Blue" },
      { "#A5CFD5", "Plume" },
      { "#A6594C", "Redwood" },
      { "#A692BA", "Viola" },
      { "#A6997A", "Olive Gray" },
      { "#A73340", "American Beauty" },
      { "#A767A2", "Iris Orchid" },
      { "#A7AE9E", "Desert Sage" },
      { "#A89A8E", "Cobblestone" },
      { "#A89A91", "Goat" },
      { "#A89C94", "Atmosphere" },
      { "#A8B0AE", "Puritan Gray" },
      { "#A8C0BB", "Harbor Gray" },
      { "#A9947A", "Cornstalk" },
      { "#A99592", "Bark" },
      { "#A9AFAA", "Pigeon" },
      { "#A9C0CB", "Winter Sky" },
      { "#A9D39E", "Pistachio Green" },
      { "#AA9855", "Burnished Gold" },
      { "#AAAAC4", "Cosmic Sky" },
      { "#AACCB9", "Bird's Egg Green" },
      { "#AACEBC", "Mist Green" },
      { "#AAD5DB", "Clearwater" },
      { "#AB856F", "Tawny Brown" },
      { "#ABA798", "Abbey Stone" },
      { "#ABAFAE", "Mirage Gray" },
      { "#ACDFDD", "Blue Light" },
      { "#AD3E48", "Cardinal" },
      { "#AD4D8C", "Purple Orchid" },
      { "#AD5E99", "Radiant Orchid" },
      { "#AD8B75", "Praline" },
      { "#AD9F93", "Simply Taupe" },
      { "#ADBBA1", "Laurel Green" },
      { "#AE8774", "Café au Lait" },
      { "#AE997D", "Travertine" },
      { "#AEA393", "Plaza Taupe" },
      { "#AEA692", "Spray Green" },
      { "#AF9294", "Deauville Mauve" },
      { "#AF9A7E", "Incense" },
      { "#AFA4CE", "Lavender" },
      { "#AFAB97", "Moss Gray" },
      { "#AFAF5E", "Palm" },
      { "#AFDDCC", "Brook Green" },
      { "#B06455", "Aragon" },
      { "#B0846A", "Camel" },
      { "#B085B7", "African Violet" },
      { "#B0879B", "Orchid Haze" },
      { "#B0B454", "Green Oasis" },
      { "#B0B487", "Winter Pear" },
      { "#B0D3D1", "Icy Morn" },
      { "#B19664", "Antelope" },
      { "#B19D8D", "Light Taupe" },
      { "#B1A992", "Eucalyptus" },
      { "#B2AC88", "Sage Green" },
      { "#B2B6AC", "Mineral Gray" },
      { "#B2CFBE", "Gossamer Green" },
      { "#B2D4DD", "Blue Glow" },
      { "#B34646", "Baked Apple" },
      { "#B35457", "Mineral Red" },
      { "#B3573F", "Autumn Glaze" },
      { "#B35A66", "Baroque Rose" },
      { "#B37256", "Sunburn" },
      { "#B38B71", "Macaroon" },
      { "#B39F8D", "Gilded Beige" },
      { "#B3ADA7", "Dove" },
      { "#B3B17B", "Weeping Willow" },
      { "#B44E5D", "Holly Berry" },
      { "#B47B77", "Old Rose" },
      { "#B4C8C2", "Surf Spray" },
      { "#B4D3B2", "Pastel Green" },
      { "#B5332E", "Molten Lava" },
      { "#B5684C", "Autumn Leaf" },
      { "#B5817D", "Ash Rose" },
      { "#B59E5F", "Antique Gold" },
      { "#B5ACAB", "Ashes of Roses" },
      { "#B5B644", "Apple Green" },
      { "#B5BAB6", "Storm Gray" },
      { "#B5BF50", "Bright Chartreuse" },
      { "#B5C1A5", "Celadon Green" },
      { "#B5CBBB", "Subtle Green" },
      { "#B5CED4", "Starlight Blue" },
      { "#B5CEDF", "Omphalodes" },
      { "#B63753", "Raspberry Wine" },
      { "#B65F9A", "Rosebud" },
      { "#B68A3A", "Harvest Gold" },
      { "#B793C0", "Sheer Lilac" },
      { "#B7A793", "Humus" },
      { "#B7A9AC", "Cloud Gray" },
      { "#B7B17A", "Leek Green" },
      { "#B7C0D7", "Xenon Blue" },
      { "#B88AAC", "Smoky Grape" },
      { "#B89B72", "Lark" },
      { "#B8A99A", "Oxford Tan" },
      { "#B8AD9E", "Feather Gray" },
      { "#B8AF23", "Citronelle" },
      { "#B8CCBA", "Celadon" },
      { "#B99BC5", "Crocus Petal" },
      { "#B9A023", "Antique Moss" },
      { "#B9EAB3", "Patina Green" },
      { "#BA6B57", "Copper Coin" },
      { "#BA9F99", "Adobe Rose" },
      { "#BAA38B", "Sesame" },
      { "#BAAFBC", "Iris" },
      { "#BAB8D3", "Purple Heather" },
      { "#BABC72", "Green Banana" },
      { "#BABFBC", "Metal" },
      { "#BAE1D3", "Honeydew" },
      { "#BB4A4D", "Cranberry" },
      { "#BB4F35", "Burnt Ochre" },
      { "#BBB1A8", "Chateau Gray" },
      { "#BBC1CC", "Gray Dawn" },
      { "#BC2B3D", "Scarlet" },
      { "#BC4869", "Carmine" },
      { "#BCA4CB", "Lavendula" },
      { "#BCA66A", "Southern Moss" },
      { "#BCA949", "Cress Green" },
      { "#BCCAB3", "Bok Choy" },
      { "#BCE3DF", "Bleached Aqua" },
      { "#BD4275", "Lilac Rose" },
      { "#BD5745", "Mecca Orange" },
      { "#BD7B74", "Desert Sand" },
      { "#BD8B69", "Sandstorm" },
      { "#BD9865", "Pale Gold" },
      { "#BDABBE", "Lavender Frost" },
      { "#BDACA3", "Mushroom" },
      { "#BDB0D0", "Pastel Lilac" },
      { "#BDB369", "Golden Green" },
      { "#BE9CC1", "Lupine" },
      { "#BEB7B0", "Silver Cloud" },
      { "#BEBDBD", "Vapor Blue" },
      { "#BED3BB", "Spray" },
      { "#BF1932", "True Red" },
      { "#BF1945", "Barberry" },
      { "#BF6464", "Faded Rose" },
      { "#BFA387", "Candied Ginger" },
      { "#BFA77F", "Taos Taupe" },
      { "#BFB4CB", "Orchid Petal" },
      { "#BFB9A3", "Tidal Foam" },
      { "#BFC8C3", "Smoke" },
      { "#C08768", "Toasted Nut" },
      { "#C0CBA1", "Seedling" },
      { "#C0CEDA", "Ballad Blue" },
      { "#C0D725", "Lime Punch" },
      { "#C17FB5", "Violet" },
      { "#C19552", "Amber Gold" },
      { "#C1BCAC", "Pelican" },
      { "#C1CCC2", "Pale Aqua" },
      { "#C1CEC1", "Green Lily" },
      { "#C2877B", "Rose Dawn" },
      { "#C2C18D", "Beechnut" },
      { "#C2CBB4", "Fog Green" },
      { "#C37C54", "Caramel" },
      { "#C39449", "Narcissus" },
      { "#C39B6A", "Taffy" },
      { "#C39D88", "Sirocco" },
      { "#C3BABF", "Lilac Marble" },
      { "#C3D3A8", "Reed" },
      { "#C3DBD4", "Glacier" },
      { "#C47E5A", "Copper" },
      { "#C4962C", "Tawny Olive" },
      { "#C4AB86", "Croissant" },
      { "#C4B6A6", "Cement" },
      { "#C4D1C2", "Dewkist" },
      { "#C51959", "Bright Rose" },
      { "#C5A253", "Sauterne" },
      { "#C5A582", "Lattè" },
      { "#C5AE91", "Warm Sand" },
      { "#C5AEB1", "Burnished Lilac" },
      { "#C5AECF", "Orchid Bloom" },
      { "#C5B1A0", "Moonlight" },
      { "#C5BBAE", "Peyote" },
      { "#C5C0D0", "Lavender Blue" },
      { "#C5C5C5", "Lunar Rock" },
      { "#C5CC7B", "Celery Green" },
      { "#C5CF98", "Lily Green" },
      { "#C5CFB6", "Tender Greens" },
      { "#C65D52", "Burnt Sienna" },
      { "#C68F65", "Butterum" },
      { "#C6973F", "Golden Spice" },
      { "#C6A4A4", "Pale Mauve" },
      { "#C71F2D", "High Risk Red" },
      { "#C74375", "Fuchsia Rose" },
      { "#C79685", "Café Crème" },
      { "#C7B63C", "Warm Olive" },
      { "#C7E5DF", "Moonlight Jade" },
      { "#C84C61", "Claret Red" },
      { "#C86733", "Burnt Orange" },
      { "#C86B3C", "Apricot Orange" },
      { "#C8B273", "Rich Gold" },
      { "#C92351", "Rose Red" },
      { "#C96551", "Ginger" },
      { "#C9A86A", "Fall Leaf" },
      { "#C9DCDC", "Whispering Blue" },
      { "#CA628F", "Ibis Rose" },
      { "#CA6C56", "Langoustino" },
      { "#CA9456", "Honey Yellow" },
      { "#CABEB5", "Gray Morn" },
      { "#CAC2B9", "Pumice Stone" },
      { "#CAC5C2", "Wind Chime" },
      { "#CACCCB", "Dawn Blue" },
      { "#CADEA5", "Butterfly" },
      { "#CBBFA2", "Gravel" },
      { "#CBC1AE", "Oyster Gray" },
      { "#CBD5B1", "Seafoam Green" },
      { "#CC4385", "Raspberry Rose" },
      { "#CC7357", "Dusted Clay" },
      { "#CCA67F", "Sand" },
      { "#CCDAD7", "Chalk Blue" },
      { "#CD7E4D", "Apricot Buff" },
      { "#CDA323", "Lemon Curry" },
      { "#CDB2A5", "Rose Dust" },
      { "#CDD78A", "Lime Sherbet" },
      { "#CE4D42", "Paprika" },
      { "#CE5E9A", "Phlox Pink" },
      { "#CE8E8B", "Rosette" },
      { "#CEBAA8", "Smoke Gray" },
      { "#CEC3D2", "Orchid Hush" },
      { "#CF9C63", "Oak Buff" },
      { "#CF9F52", "Bright Gold" },
      { "#CFC486", "Shadow Green" },
      { "#CFC8BD", "Rainy Day" },
      { "#CFDFDB", "Morning Mist" },
      { "#D0D3B7", "Aloe Wash" },
      { "#D18E54", "Buckskin" },
      { "#D1969A", "Blush" },
      { "#D198C5", "Orchid" },
      { "#D19C97", "Rose Tan" },
      { "#D1A054", "Honey Gold" },
      { "#D1ACCE", "Orchid Bouquet" },
      { "#D1BE9B", "Boulder" },
      { "#D1D5D0", "Foggy Dew" },
      { "#D2386C", "Raspberry Sorbet" },
      { "#D28FB0", "Moonlite Mauve" },
      { "#D29B83", "Dusty Coral" },
      { "#D2B49C", "Toasted Almond" },
      { "#D2C2AC", "Frosted Almond" },
      { "#D2CFC4", "Silver Birch" },
      { "#D2E8E0", "Aqua Glass" },
      { "#D33479", "Fuchsia Purple" },
      { "#D3507A", "Pink Flambé" },
      { "#D37F6F", "Tawny Orange" },
      { "#D38377", "Terra Cotta" },
      { "#D39237", "Sunflower" },
      { "#D3D95F", "Limeade" },
      { "#D4AE40", "Ceylon Yellow" },
      { "#D4CACD", "Gray Lilac" },
      { "#D5BA98", "Beige" },
      { "#D5D593", "Mellow Green" },
      { "#D5D717", "Sulphur Spring" },
      { "#D687BA", "Cyclamen" },
      { "#D6AF66", "Ochre" },
      { "#D6C69A", "Parsnip" },
      { "#D77E70", "Crabapple" },
      { "#D7942D", "Golden Orange" },
      { "#D7B8AB", "Cameo Rose" },
      { "#D7CAB0", "Wood Ash" },
      { "#D7CDCD", "Lilac Ash" },
      { "#D7D0C0", "Bone White" },
      { "#D7D7C7", "Silver Green" },
      { "#D8A1C4", "Pastel Lavender" },
      { "#D8AAB7", "Pink Nectar" },
      { "#D93744", "Bittersweet" },
      { "#D94F70", "Honeysuckle" },
      { "#D979A2", "Wild Orchid" },
      { "#D9922E", "Autumn Blaze" },
      { "#D9AFCA", "Pink Lavender" },
      { "#DAB965", "Misted Yellow" },
      { "#DBCCB5", "Crème Brûlée" },
      { "#DC3855", "Teaberry" },
      { "#DC5B62", "Rose of Sharon" },
      { "#DC7178", "Tea Rose" },
      { "#DC793E", "Amberglow" },
      { "#DCD494", "Lemon Grass" },
      { "#DD3848", "Hibiscus" },
      { "#DD4124", "Tangerine Tango" },
      { "#DDE0DF", "Barely Blue" },
      { "#DE5B8C", "Shocking Pink" },
      { "#DE9BC4", "Lilac Chiffon" },
      { "#DECDBE", "Sand Dollar" },
      { "#DF7253", "Flamingo" },
      { "#DFB19B", "Pink Sand" },
      { "#E04F80", "Fandango Pink" },
      { "#E0D0DB", "Orchid Ice" },
      { "#E0E4D9", "Ice" },
      { "#E1D590", "Lima Bean" },
      { "#E24666", "Rouge Red" },
      { "#E2583E", "Tigerlily" },
      { "#E290B2", "Rosebloom" },
      { "#E29A86", "Shrimp" },
      { "#E29D94", "Coral Almond" },
      { "#E2B051", "Yolk Yellow" },
      { "#E2BEA2", "Amberlight" },
      { "#E2E6E0", "Bluewash" },
      { "#E35B8F", "Carmine Rose" },
      { "#E4445E", "Paradise Pink" },
      { "#E47127", "Russet Orange" },
      { "#E4C7B8", "Cream Tan" },
      { "#E4D7C5", "White Swan" },
      { "#E5D0CF", "Mauve Chalk" },
      { "#E5EBE3", "Summer Shower" },
      { "#E6BD8F", "Golden Straw" },
      { "#E78B90", "Strawberry Ice" },
      { "#E7D3AD", "Banana Crepe" },
      { "#E7DF99", "Chardonnay" },
      { "#E7EACB", "Sylvan Green" },
      { "#E881A6", "Aurora Pink" },
      { "#E8B5CE", "Sweet Lilac" },
      { "#E96A97", "Azalea Pink" },
      { "#E9EAC8", "Green Essence" },
      { "#EA6759", "Emberglow" },
      { "#EA6B6A", "Porcelain Rose" },
      { "#EB3C27", "Cherry Tomato" },
      { "#EBA851", "Beeswax" },
      { "#EBCF89", "Sundress" },
      { "#EC6A37", "Mandarin Orange" },
      { "#EC9ABE", "Begonia Pink" },
      { "#ECA825", "Old Gold" },
      { "#ECAA79", "Apricot Nectar" },
      { "#ED7A9E", "Pink Carnation" },
      { "#EDCAB5", "Bisque" },
      { "#EDDCC9", "White Smoke" },
      { "#EDE3D2", "Antique White" },
      { "#EDE6DE", "Jet Stream" },
      { "#EE819F", "Morning Glory" },
      { "#EEA0A6", "Pink Icing" },
      { "#EFC1D6", "Pink Lady" },
      { "#EFE0CD", "Buttercream" },
      { "#EFE1A7", "French Vanilla" },
      { "#EFEBE7", "White Alyssum" },
      { "#EFEFE8", "Star White" },
      { "#F0A1BF", "Prism Pink" },
      { "#F0C05A", "Mimosa" },
      { "#F0D8CC", "Pink Champagne" },
      { "#F0DEBD", "Alabaster Gleam" },
      { "#F0DFCC", "Pearled Ivory" },
      { "#F0EADA", "Vanilla Ice" },
      { "#F0EEE4", "Marshmallow" },
      { "#F0EEE9", "Cloud Dancer" },
      { "#F19035", "Apricot" },
      { "#F1BD89", "Apricot Cream" },
      { "#F1E8DF", "Gardenia" },
      { "#F25F66", "Dubarry" },
      { "#F2AB46", "Artisan's Gold" },
      { "#F2B2AE", "Blossom" },
      { "#F2CFDC", "Ballerina" },
      { "#F2D3BC", "Nude" },
      { "#F2D6AE", "Cornhusk" },
      { "#F2D8CD", "Soft Pink" },
      { "#F2E6B1", "Pastel Yellow" },
      { "#F2E8DA", "Pristine" },
      { "#F2F0EB", "Snow White" },
      { "#F35B53", "Hot Coral" },
      { "#F3774D", "Coral Rose" },
      { "#F38554", "Autumn Sunset" },
      { "#F3BBCA", "Orchid Pink" },
      { "#F3BF08", "Lemon" },
      { "#F3C12C", "Freesia" },
      { "#F3DFCA", "Ecru" },
      { "#F3DFD7", "Angel Wing" },
      { "#F3E0BE", "Vanilla Custard" },
      { "#F3E0D6", "Powder Puff" },
      { "#F3EAC3", "Pear Sorbet" },
      { "#F3ECE0", "Egret" },
      { "#F47327", "Persimmon Orange" },
      { "#F4A6A3", "Peaches N' Cream" },
      { "#F4C29F", "Almond Cream" },
      { "#F4C6C3", "English Rose" },
      { "#F4C9B1", "Bellini" },
      { "#F4CEC5", "Pearl Blush" },
      { "#F4DEDE", "Heavenly Pink" },
      { "#F4E1C1", "Vanilla" },
      { "#F4E1E6", "Shrinking Violet" },
      { "#F4E3B5", "Anise Flower" },
      { "#F4E4C1", "Almond Oil" },
      { "#F4F5F0", "Bright White" },
      { "#F56733", "Golden Poppy" },
      { "#F56C73", "Sugar Coral" },
      { "#F5D1C8", "Cloud Pink" },
      { "#F5D7AF", "Apricot Gelato" },
      { "#F5E3E2", "Delicacy" },
      { "#F5ECD2", "Winter White" },
      { "#F67866", "Persimmon" },
      { "#F6909D", "Geranium Pink" },
      { "#F6D155", "Primrose Yellow" },
      { "#F6DBD8", "Rosewater" },
      { "#F6E199", "Lemon Meringue" },
      { "#F6E3B4", "Flan" },
      { "#F6E4D9", "Cream Pink" },
      { "#F6E5DB", "Sheer Pink" },
      { "#F6EBC8", "Lemon Icing" },
      { "#F7969E", "Flamingo Pink" },
      { "#F7B26A", "Chamois" },
      { "#F7BF68", "Golden Cream" },
      { "#F7C8C2", "Seashell Pink" },
      { "#F7CAC9", "Rose Quartz" },
      { "#F7D000", "Empire Yellow" },
      { "#F7D1D1", "Pink Dogwood" },
      { "#F88180", "Shell Pink" },
      { "#F8A39D", "Candlelight Peach" },
      { "#F8D5B8", "Tender Peach" },
      { "#F8D7DD", "Barely Pink" },
      { "#F97272", "Georgia Peach" },
      { "#F99471", "Cadmium Orange" },
      { "#F9C2CD", "Rose Shadow" },
      { "#F9D857", "Lemon Zest" },
      { "#F9DBD8", "Pearl" },
      { "#FA9A85", "Peach Pink" },
      { "#FAB75A", "Amber Yellow" },
      { "#FAC8C3", "Gossamer Pink" },
      { "#FACE6D", "Yarrow" },
      { "#FAE03C", "Buttercup" },
      { "#FAE199", "Pale Banana" },
      { "#FB8B23", "Flame Orange" },
      { "#FB9F93", "Peach Amber" },
      { "#FBBDAF", "Peach Melba" },
      { "#FBD3D9", "Blushing Bride" },
      { "#FBD8C9", "Scallop Shell" },
      { "#FC8F9B", "Conch Shell" },
      { "#FC9E21", "Radiant Yellow" },
      { "#FD6F3B", "Carrot" },
      { "#FDAC53", "Marigold" },
      { "#FDC3C6", "Crystal Rose" },
      { "#FDD878", "Lemon Drop" },
      { "#FE8863", "Melon" },
      { "#FEAEA5", "Apricot Blush" },
      { "#FED777", "Snapdragon" },
      { "#FEE715", "Blazing Yellow" },
      { "#FF6F61", "Living Coral" },
      { "#FF7913", "Oriole" },
      { "#FF8576", "Fusion Coral" },
      { "#FF8656", "Nectarine" },
      { "#FF8812", "Autumn Glory" },
      { "#FFA64F", "Blazing Orange" },
      { "#FFB2A5", "Peach Pearl" },
      { "#FFB865", "Warm Apricot" },
      { "#FFBB7C", "Buff Orange" },
      { "#FFC4B2", "Tropical Peach" },
      { "#FFC4BC", "Impatiens Pink" },
      { "#FFC66E", "Pale Marigold" },
      { "#FFD02E", "Dandelion" },
      { "#FFD400", "Cyber Yellow" },
      { "#FFD662", "Aspen Gold" },
      { "#FFDA29", "Vibrant Yellow" }
    };
  }
}